### ISSUE TITLE
Provide script to set the subscriptionKey on an API in Azure API Management

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#39]
**Is your feature request related to a problem? Please describe.**
Currently setting the subscriptionKeyParameterNames within an ARM-template does not work properly yet to override the default names assigned to the subscriptionKey header/query-parameter.

**Describe the solution you'd like**
Use the script written by Tom to override the default values.

**Additional context**
The PS-script can be found here:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FApim-SetAuthenticationHeadersForApi.ps1

**Comment by tomkerkhove** [comment]
This issue should be fixed in ARM now - https://azure.microsoft.com/en-us/updates/azure-api-management-update-may-2020/

**Comment by mbraekman** [comment]
Unfortunately, this fix still isn't working when creating a new API.
